# Generated by Django 3.1.7 on 2021-03-04 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_imageprocessor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='name',
            new_name='About',
        ),
    ]
